name: Test

on: [push]

jobs:

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: [stable, nightly, 1.51.0]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args:  --verbose --all
